name: ✨ Feature Request
description: Suggest a new feature or enhancement for Kyno
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Your feedback helps make Kyno better for everyone.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to make sure this feature hasn't been requested already
          required: true
        - label: I have checked the roadmap/announcements to see if this feature is already planned
          required: true

  - type: textarea
    id: feature_summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see
      placeholder: "Briefly describe the feature you're requesting..."
    validations:
      required: true

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of how you envision this feature working
      placeholder: "Describe the feature in detail, including how users would interact with it..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use of the app
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, research, or examples that might help with this feature request
      placeholder: "Any additional information that might be helpful..."